### ISSUE TITLE
Interpolation params with string keys not working in 1.6

### ISSUE THREAD

**Issue by mwean** [ruby-i18n/i18n#478]
## What I tried to do

```ruby
I18n.t("Hi %{name}", "name" => 'David')
```

## What I expected to happen

`"Hi David"`

## What actually happened

`"Hi %{name}"`

## Versions of i18n, rails, and anything else you think is necessary

1.6.0

----

It looks like this changed in [this commit](https://github.com/ruby-i18n/i18n/commit/6f3d428a5a0055ce61c5d069ce4782c4d1958bf8) where the arguments to `translate` were switched to keyword args (`**options`), which doesn't include string keys. We have a bunch of translations that use options hashes with string keys, which broke with the 1.6 update. I assume that wasn't intentional because it was a minor version bump.

Thanks!

**Comment by radar** [comment]
Hey @mwean, thanks for letting us know about this. There did not appear to be any tests broken by the change you pointed at, so I think this was an unintentional behaviour of how i18n used to work. It seems like you're using it for simply interpolation features within strings. I think you could reproduce this behaviour with code as simple as:

```
>> input = "Hi %{name}"
=> "Hi %{name}"
>> args = {name: "Ryan"}
=> {:name=>"Ryan"}
>> input.gsub(/%{(.*?)}/) { args[$1.to_sym] }
```

Is there a particular reason that you're relying on `i18n` here to behave in this particular way?

**Comment by mwean** [comment]
Oh, that was just an example from the specs. We're actually using dynamic translation keys along with the string interpolation. I was able to work around the issue by just calling `symbolize_keys` on the options, but it might be worth addressing since I can imagine other people running into it.

**Comment by radar** [comment]
Ah of course `symbolize_keys` would fix it here. Good thinking. 

Let's leave this issue for now. If more people get bitten by it, then I think we can spend some time looking into it.

**Comment by stevenjackson** [comment]
Just wanted to chime in that I ran into this for a slightly more obscure use-case.  In my case the interpolations were within an `ActiveSupport::HashWithIndifferentAccess` in a rails app. `HashWithIndifferentAccess` converts everything to string keys, so my code "looked" like it was using symbol keys:
`I18n.t("foo.bar.baz", data.merge(interpolated_value: "generated"))`

I started a PR to try and cover this case, but it ended up getting out of hand.  Essentially the reason this worked pre-1.6 is because the `HashWithIndifferentAccess` would end up getting passed all the way to here: 
 https://github.com/ruby-i18n/i18n/blob/ef6bbb345bcd5a712f66812063d367bed92a2229/lib/i18n/interpolate/ruby.rb#L28
`key?` will return true for both symbol or string keys.

I don't have a great solution, but it might be worth putting a warning on the 1.6 release notes.
