### ISSUE TITLE
Unable to see changelog in Releases

### ISSUE THREAD

**Issue by jhanggi** [ruby-i18n/i18n#512]
## What I tried to do

See what has changed in the new versions. CHANGELOG.md points me to the releases page. When I visit https://github.com/ruby-i18n/i18n/releases the last release I see is 1.6.0.

## What I expected to happen

I would love to see what's new! I can see the newer tags, but not as easy to read/understand as "Major updates"/"Bugfixes / other improvements", etc.

## What actually happened

The last release is 1.6.0

I was affected by #510 so I was trying to get a handle on what changed when. Thanks!

**Comment by radar** [comment]
Thanks! Fixed this up today. I've just been particularly lazy in building them up. 

FYI: The #510 issue was introduced in I18n 1.7.0, but then was fixed in I18n 1.8.2. If you're using I18n > 1.8.2 then this issue should remain fixed. There's now been a regression test introduced in 1b5e34553003ca3b42b842769e86c98d5e3b71d4 which should prevent this particular behaviour from reoccurring. I'm sorry that this slipped out in the first place!

**Comment by jhanggi** [comment]
Great. Thanks for the update!
